[package]
name = "server"
version = "0.1.0"
authors = ["Undin <a.pendryak@yandex.ru>"]

[dependencies]
diesel = { version = "0.11", features = ["postgres"] }
diesel_codegen = { version = "0.11", features = ["postgres"] }
dotenv = "0.8"
r2d2 = "0.7"
r2d2-diesel = "0.11"
reqwest = "0.4"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
threadpool = "1.0"
